server:
  port: 8080

spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  datasource:
    url: jdbc:h2:tcp://localhost/~/restApi
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl.auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: false
  messages:
    basename: i18n/exception
    encoding: UTF-8
#  profiles:
#    include: oauth